import { Allura } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import "./globals.css";
import Navbar from "./Navbar";
import Footer from "./Footer";

// const inter = Inter({ subsets: ["latin"] });

const allura = Allura({
  weight:'400',
  subsets:['latin'],
  variable:'--font-allura'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={allura.variable}>
        <Navbar />
        <AppRouterCacheProvider>
          {children}
        </AppRouterCacheProvider>
        <Footer />
      </body>
    </html>
  );
}
